remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-include-cache

title: SPA Logs
description: A blog/tutorial documenting my struggle to make a single page application using modern technologies

search_enabled: true
aux_links:
    "Follow me on GitHub":
      - "//github.com/lucasMontenegro"
